<?php
    $_code = $this->getCode();
    $elementIndex = $this->getElementIndex();
    $elementId = $_code . "_boleto_". $elementIndex;
    $elementClass = $_code . "_boleto";
    $showValueInput = $this->getShowValueInput();
    $grandTotal = $this->getGrandTotal();
?>

<div class="input-box">
    <h6><?php echo $this->__('Billet') . ' ' . $elementIndex; ?></h6>
    <?php if($showValueInput === true) : ?>
        <div class="input-box">
            <label><?php echo $this->__('Value'); ?> (Ex: 100.50)<span class="required"></span></label><br/>
            <input
                    type="number"
                    step=".01"
                    min="0"
                    id="<?php echo $elementId; ?>_value"
                    name="payment[<?php echo $elementId; ?>_value]"
                    title="Value (Ex: 100,50)"
                    class="required-entry multipayment-value-input"
                    value="">
        </div>
    <?php else: ?>
        <div class="input-box">
            <input
                    type="hidden"
                    id="<?php echo $elementId; ?>_value"
                    name="payment[<?php echo $elementId; ?>_value]"
                    value="<?php echo $grandTotal; ?>">
        </div>
    <?php endif; ?>
    <label><?php echo $this->__('Tax/VAT'); ?><span class="required"></span></label><br/>
    <input
            type="text"
            id="<?php echo $elementId; ?>_taxvat"
            name="payment[<?php echo $elementId; ?>_taxvat]"
            class="<?php echo $elementClass; ?>_validate-mundipagg-cpf required-entry"
    />

    <!-- Multi buyer -->

    <div class="input-box">

        <input
                type="checkbox"
                id="<?php echo "$elementId"?>_multi_buyer_enabled"
                name="payment[<?php echo "$elementId"?>_multiBuyerEnabled]"
        >
        <label for="<?php echo "$elementId"?>_multi_buyer_enabled"><?php echo $this->__('Fill other buyer data'); ?></label>
    </div>
    <br>
    <h3><?php echo $this->__('Fill other buyer data'); ?></h3>

    <div class="input-box">
        <label><?php echo $this->__('Full name'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_name"
                name="payment[<?php echo "$elementId"?>_multiBuyerName]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('E-mail'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_email"
                name="payment[<?php echo "$elementId"?>_multiBuyerEmail]"
                class="required-entry"
                value="">
    </div>

    <label><?php echo $this->__('Tax/VAT'); ?><span class="required"></span></label><br/>
    <input
            type="text"
            id="<?php echo $elementId; ?>_multi_buyer_taxvat"
            name="payment[<?php echo $elementId; ?>_multiBuyerTaxvat]"
            class="<?php echo $elementClass; ?>_validate-mundipagg-cpf required-entry"
    />

    <div class="input-box">
        <label><?php echo $this->__('Zipcode'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_zip_code"
                name="payment[<?php echo "$elementId"?>_multiBuyerZipCode]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('Street'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_street"
                name="payment[<?php echo "$elementId"?>_multiBuyerStreet]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('Number'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_number"
                name="payment[<?php echo "$elementId"?>_multiBuyerNumber]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('Complement'); ?></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_complement"
                name="payment[<?php echo "$elementId"?>_multiBuyerComplement]"
                class=
                value="">
    </div>


    <div class="input-box">
        <label><?php echo $this->__('Neighborhood'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_neighborhood"
                name="payment[<?php echo "$elementId"?>_multiBuyerNeighborhood]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('City'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_city"
                name="payment[<?php echo "$elementId"?>_multiBuyerCity]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('State'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_state"
                name="payment[<?php echo "$elementId"?>_multiBuyerState]"
                class="required-entry"
                value="">
    </div>

    <div class="input-box">
        <label><?php echo $this->__('Country'); ?> <span class="required"></span></label><br/>
        <input
                type="text"
                id="<?php echo "$elementId"?>_multi_buyer_country"
                name="payment[<?php echo "$elementId"?>_multiBuyerCountry]"
                class="required-entry"
                value="">
    </div>
</div>
<br /><hr />
