<?php $billetData = $this->getBilletData(); ?>
<br />
<?php if(!empty($billetData)) : ?>
    <?php foreach($billetData as $billet) : ?>
        <?php echo sprintf(
            $this->__(
                "Click <a href='%s'>here</a>" .
                " to show your billet for <strong>%s</strong> payment."
            ),
            $billet['url'],
            $billet['value']);
        ?>
      <br />
    <?php endforeach; ?>
<?php endif; ?>