<?php
$_code = $this->getMethodCode();
$structure = $this->getStructure();
$orderTotal = $this->getGrandTotal();
?>
<fieldset>
    <ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
        <li>
            <div>
                <ul >
                    <?php foreach($structure as $element): ?>
                    <li style="clear:both">
                        <?php echo $this->getPartialHtml($element); ?>
                        <?php echo $this->getMultiBuyerHtml($element); ?>
                        <br /><hr />
                    </li>
                    <?php endforeach; ?>
                    <input type="hidden" id="baseUrl" value="<?php echo Mage::getUrl('');?>"/>
                </ul>
            </div>
        </li>
    </ul>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            initPaymentMethod('<?php echo $_code; ?>','<?php echo $orderTotal; ?>');
        });
    </script>
</fieldset>
