<?php
$_code = $this->getMethodCode();
$structure = $this->getStructure();
?>
<fieldset>
    <ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
        <li>
            <div>
                <ul >
                    <?php foreach($structure as $element) : ?>
                    <li style="clear:both">
                        <?php echo $this->getPartialHtml($element);?>
                    </li>
                    <?php endforeach; ?>
                    <input type="hidden" id="baseUrl" value="<?php echo Mage::getUrl('');?>"/>
                </ul>
            </div>
        </li>
    </ul>
    <script type="javascript">

        initPaymentMethod('<?php echo $_code; ?>');

        //cc token
        //validações
        //balanceamento de value
    </script>
</fieldset>
