<?php $_code = $this->getMethodCode(); ?>
<fieldset>
    <ul id="payment_form_<?php echo $_code; ?>" style="display:none;"
        <li>
            <div id="paymentmodule_creditcard">
                <ul >
                    <li style="clear:both">
                        <div class="input-box" data-mundicheckout-form data-pkkey="<?php echo $this->getPublicKey(); ?>" id="tokenDiv">
                            <label for="">Holder name<span class="required">*</span></label>
                            <input type="text" data-mundicheckout-input="holder_name" class="required-entry teste1"><br>

                            <label for="">Number<span class="required">*</span></label>
                            <input type="text" data-mundicheckout-input="number" class="required-entry teste2"><span data-mundicheckout-input="brand"></span><br>

                            <label for="">Expiration month<span class="required">*</span></label>
                            <input type="text" data-mundicheckout-input="exp_month" class="required-entry teste3"><br>

                            <label for="">Expiration year<span class="required">*</span></label>
                            <input type="text" data-mundicheckout-input="exp_year" class="required-entry teste4"><br>

                            <label for="">CVV<span class="required">*</span></label>
                            <input type="text" data-mundicheckout-input="cvv" class="required-entry teste5"><br>
                        </div>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</fieldset>
