<?php
$_code = $this->getMethodCode();
$structure = $this->getStructure();
?>
<fieldset>
    <ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
        <li>
            <div>
                <ul >
                    <?php foreach($structure as $element) : ?>
                    <li style="clear:both">
                        <?php echo $this->getPartialHtml($element);?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </li>
    </ul>
    <script type="javascript">

    </script>
</fieldset>
